spring.application.name=qa-management-api

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/qa_management_db
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

security.jwt.secret=${QAMS_JWT_SECRET}
security.jwt.expiration-ms=${QAMS_JWT_EXPIRATION_MS:86400000}
